<?php

namespace CV\CvBundle\Repository;

/**
 * ExperiencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperiencesRepository extends \Doctrine\ORM\EntityRepository
{
}
