<?php

namespace CV\CvBundle\Repository;

/**
 * InfogeneraleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfogeneraleRepository extends \Doctrine\ORM\EntityRepository
{
}
