<?php

namespace CV\CvBundle\Repository;

/**
 * RefererencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefererencesRepository extends \Doctrine\ORM\EntityRepository
{
}
